version: "3"

includes:
  app:
    taskfile: ./app/taskfile.yml
    dir: ./app/
  infra:
    taskfile: ./infra/taskfile.yml
    dir: ./infra/

tasks:
  default:
    aliases: [help]
    desc: Prints help message and list all
    cmds:
      - task -l
    silent: true

  test:
    desc: Run tests for all projects
    cmds:
      - task: "app:test"

  format:
    desc: Autoformats all projects
    cmds:
      - task: "app:format"
      - task: "infra:format"

  lint:
    desc: Check for code smells in all projects
    cmds:
      - task: "app:lint"

  pull:
    desc: Pulls newest changes
    cmds:
      - git pull

  updateApp:
    desc: updates the image app
    cmds:
      - podman image pull ghcr.io/c0dk/stikl:main
      - systemctl restart podman-stikl-web.service

  deploy:
    desc: Pulls newest changes
    cmds:
      - task: pull
      - task: infra:deploy
      - task: updateApp