version: "3"

includes:
  api: 
    taskfile: ./api/taskfile.yml
    dir: ./api/
  infra:
    taskfile: ./infra/taskfile.yml
    dir: ./infra/

tasks:
  default:
    aliases: [help]
    desc: Prints help message and list all
    cmds:
      - task -l
    silent: true
  test:
    desc: Run tests for all projects
    cmds:
      - task: "api:test"

  format:
    desc: Autoformats all projects
    cmds:
      - task: "api:format"
      - task: "infra:format"

  lint:
    desc: Check for code smells in all projects
    cmds:
      - task: "api:lint"
