version: "3"

includes:
  api: 
    taskfile: ./api/taskfile.yml
    dir: ./api/
  webapp: 
    taskfile: ./webapp/taskfile.yml
    dir: ./webapp/

tasks:
  default:
    aliases: [help]
    desc: Prints help message and list all
    cmds:
      - task -l
    silent: true
  test:
    desc: Run tests for all projects
    cmds:
      - task: "api:test"

  format:
    desc: Autoformats  all projects
    cmds:
      - task: "api:format"
