version: '3'

tasks:
  default:
    aliases: [help]
    desc: Prints help message and list all
    cmds:
      - task -l
    silent: true
  test:
    desc: Run tests for all projects
    cmds:
      - task: 'api:test'
  format:
    aliases: [fmt]
    desc: Autoformats code
    cmds:
      - npm run format
  lint:
    desc: Checks for code smells etc
    cmds:
      - npm run lint
      - npm run check
  dev:
    desc: Runs a dev server
    cmds:
      - npm run dev
  storybook:
    desc: Runs storybook to show components
    cmds:
      - npm run storybook
