version: "3"

tasks:
  default:
    aliases: [help]
    desc: Prints help message and list all
    cmds:
      - task -l
    silent: true

  format:
    desc: auto formats all F# code
    cmds:
      - dotnet fantomas .

  test:
    desc: Runs all unit tests
    cmds:
      - dotnet test
  lint:
    desc: Checks for code smells
    cmds:
      - echo "TODO fsharplint"
      # - dotnet fsharplint lint .

  createJwt:
    desc: Creates a jwt token that can be used for testing
    cmds:
      - dotnet user-jwts create --project api/api.fsproj {{.CLI_ARGS}}
